### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bananaox**
- Added HTML and CSS to Framework Languages and Databases
- Are we okay with this team?
- #2

### CODE REVIEW

**Comment by jkutch326** [comment]
That will be necessary in some parts. I agree that we'll need markup languages for the rendering of the final user-facing product.

**Comment by mb3668** [comment]
I am very happy with this group.

**Comment by mb3668** [comment]
HTML and CSS would work good.

**Comment by bgunn7** [comment]
That sounds good to me.

**Comment by bananaox** [comment]
Team confirmed merge

**Review by jkutch326 — COMMENTED** [review]
I realize that I left a comment and not a review a little late. My original comment below stands:
"That will be necessary in some parts. I agree that we'll need markup languages for the rendering of the final user-facing product."

**Pull request merged**
